
title: menozero's journal

# description: >-

author: menozero
# email: menozero@menozero.net

github_username: menozero
twitter_username: menozero
instagram_username: menozero


url: "https://menozero.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/journal" # the subpath of your site, e.g. /blog



# theme:

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

relative_links:
  enabled:     true
  collections: false

#github:
#  - metadata

#exclude:
#  - Gemfile
#  - Gemfile.lock
#  - vendor
